### PR TITLE
[7.x] BXMSPROD-1558 @kie/lock-treatment-tool

### PR DESCRIPTION
**Pull request by Ginxo**
### JIRA

https://issues.redhat.com/browse/BXMSPROD-1558

### Referenced pull requests

* https://github.com/kiegroup/optaweb-vehicle-routing/pull/619
* https://github.com/kiegroup/optaweb-employee-rostering/pull/734

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] LTS</b>

</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Review by yurloc — CHANGES_REQUESTED** [review]
`package-lock.json` modifications.

**Review by Christopher-Chianelli — CHANGES_REQUESTED** [review]
I pretty sure this change breaks first time users doing a `mvn clean install`; if I remove node_modules, I get this error:

```
[INFO] --- frontend-maven-plugin:1.11.3:install-node-and-npm (install node and npm) @ optaweb-employee-rostering-frontend ---
[INFO] Node v12.16.2 is already installed.
[INFO] NPM 7.15.1 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.11.3:npm (lock-treatment-tool execution) @ optaweb-employee-rostering-frontend ---
[INFO] Running 'npm exec @kie/lock-treatment-tool --' in .../employee-rostering/optaweb-employee-rostering-frontend
[INFO] npm WARN exec The following package was not found and will be installed: @kie/lock-treatment-tool
[INFO] sh: line 1: locktt: command not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.445 s
[INFO] Finished at: 2021-12-10T13:15:44-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:npm (lock-treatment-tool execution) on project optaweb-employee-rostering-frontend: Failed to run task: 'npm exec @kie/lock-treatment-tool --' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
```

But if I do `npm install` outside of maven, then `mvn clean install` works (at least on main, which already have the commit merged).

**Comment by Ginxo** [comment]
> I pretty sure this change breaks first time users doing a `mvn clean install`; if I remove node_modules, I get this error:
> 
> ```
> [INFO] --- frontend-maven-plugin:1.11.3:install-node-and-npm (install node and npm) @ optaweb-employee-rostering-frontend ---
> [INFO] Node v12.16.2 is already installed.
> [INFO] NPM 7.15.1 is already installed.
> [INFO] 
> [INFO] --- frontend-maven-plugin:1.11.3:npm (lock-treatment-tool execution) @ optaweb-employee-rostering-frontend ---
> [INFO] Running 'npm exec @kie/lock-treatment-tool --' in .../employee-rostering/optaweb-employee-rostering-frontend
> [INFO] npm WARN exec The following package was not found and will be installed: @kie/lock-treatment-tool
> [INFO] sh: line 1: locktt: command not found
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  3.445 s
> [INFO] Finished at: 2021-12-10T13:15:44-05:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:npm (lock-treatment-tool execution) on project optaweb-employee-rostering-frontend: Failed to run task: 'npm exec @kie/lock-treatment-tool --' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
> ```
> 
> But if I do `npm install` outside of maven, then `mvn clean install` works (at least on main, which already have the commit merged).

I couldn't reproduce it... :thinking: 
I did with no errors...
```
cd optaweb-employee-rostering-frontend/
rm -rf node_modules
mvn clean install -DskipTests
```
can you please @Christopher-Chianelli double check it?

**Comment by yurloc** [comment]
> [INFO] Running 'npm exec @kie/lock-treatment-tool --' in .../employee-rostering/optaweb-employee-rostering-frontend
> [INFO] npm WARN exec The following package was not found and will be installed: @kie/lock-treatment-tool
> [INFO] sh: line 1: locktt: command not found

@Christopher-Chianelli I cannot reproduce it (reliably) either, although I must say I've also seen this error _a couple_ of times when reviewing the locktt upgrade PRs. But now I can't reproduce it. Not even with a fresh clone, not even with `-Dproductized`.

**Comment by Christopher-Chianelli** [comment]
@yurloc It appears a commit 2 hours ago changed the order of execution of plugins, which also would fix the issue. The same commit need to be applied to main (as it currently broken; open PR: https://github.com/kiegroup/optaweb-employee-rostering/pull/736 )

**Review by Christopher-Chianelli — APPROVED** [review]

**Comment by yurloc** [comment]
For the record, I've just updated `package-lock.json` with the state that results from running `mvn clean install -nsu` on my machine. This is _probably_ the correct state because it's identical with the state in the GHA environment as evidenced by the recently added `git diff HEAD --exit-code` check.

We've agreed on this solution with @Ginxo in https://github.com/kiegroup/optaweb-vehicle-routing/pull/619 because despite he's doing exactly the same steps and his environment seems to be configured properly, he keeps getting a different state of `package-lock.json`.

@Christopher-Chianelli I'd kindly ask you to re-review this PR, check it out locally, build the frontend module and confirm that you can't see any uncommitted modifications of `package-lock.json`. I'd like to get one more confirmation to be sure we have the correct state and can safely move forward.

Just to be clear, the goal here is to keep `package-lock.json` in the correct state to avoid conflicts between multiple contributors collaborating on this project.

**Comment by Christopher-Chianelli** [comment]
@yurloc doing a `git diff` after a `mvn clean install` on current commit was the first thing I did before approving this PR; no package-lock.json changes for me; SHA1 hash:

```bash
$ sha1sum package-lock.json
8ec282491d08df79c299335489626b5460ecfb92  package-lock.json
```

**Review by yurloc — APPROVED** [review]

**Pull request merged**
