### PR TITLE
Upgrade frontend-maven-plugin for Apple Silicon support

### PR DESCRIPTION
**Pull request by teejae**
- Upgrade frontend-maven-plugin `1.8.0` -> `1.11.3`, which correctly installs npm on Apple SIlicon.

### JIRA

https://github.com/kiegroup/optaweb-employee-rostering/issues/608

### Referenced pull requests

Same version in optaweb-vehicle-routing
https://github.com/kiegroup/optaweb-vehicle-routing/pull/616

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] LTS</b>

</details>

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
There appears to be a format change in the `package-lock.json` file; in particular:

- `lockfileVersion` 1 - > 2
- `package` -> `node_modules/package`
- Removed resolved, integrity fields
- requires -> dependencies for certain packages

I would prefer the Lockfile to be updated in a separate PR (The change is too large for me to audit). The plugin version update look good, but I have no way to verify locally (minus looking at change logs and assuming they are accurate) (the earliest version for Apple Silicon support is `1.11.0`, and the latest public release is `1.12.0`, according to the Change log).

**Comment by Christopher-Chianelli** [comment]
jenkins test this

**Comment by teejae** [comment]
@Christopher-Chianelli i've just removed the package-lock commit, leaving only the plugin upgrade. i agree that it should be a separate PR. however, keep in mind that anyone who runs this new version will see that file change automatically.

**Comment by yurloc** [comment]
@teejae Sorry for the inconvenience, `package-lock.json` is temporarily out of sync due to #730 and it's completely unrelated to the Frontend plugin update, which is a good idea.

**Comment by teejae** [comment]
@yurloc so is there something i need to do to handle the syncing? or will someone else be handling that?

**Review by Christopher-Chianelli — APPROVED** [review]

**Pull request merged**
