### PR TITLE
BXMSPROD-580: frontend-maven-plugin version pointing to the centralised one

### PR DESCRIPTION
**Pull request by Ginxo**
Requires: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1117

BXMSPROD-580

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Ignoring Travis since it doesn't know how to handle group PR; wait until https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1117 is merged before merging.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@Christopher-Chianelli the travis CI still failing, not sure if or how it relates to this change

**Comment by Christopher-Chianelli** [comment]
@mareknovotny, this is a group PR, correct? Jenkins take into account and merge all group PR before it runs, Travis does not. Since Jenkins pass, this PR is good to merge if the other group PR's are good to merge. (The failure have to do with a missing plugin version)

**Comment by mareknovotny** [comment]
ok, yes, I merged all other PRs and tried to rerun the Travis CI, but it seems failed again, so I was not sure how that missing version in deps is related or there is some other problem

**Comment by Christopher-Chianelli** [comment]
@mareknovotny I think I know the issue; Travis-CI does not use the -U flag in the download dependencies, so it is using the cache (which has the old version of kie-parent without the version property)

**Comment by mareknovotny** [comment]
ok, so I think we can merge this now

**Pull request merged**
