### PR TITLE
[8.10.x] PLANNER-2504 remove final modifier (workaround)

### PR DESCRIPTION
**Pull request by rsynek**
Cherry-pick of https://github.com/kiegroup/optaweb-employee-rostering/pull/671

### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by yurloc — APPROVED** [review]

**Comment by triceo** [comment]
Should the build chain be failing?

**Comment by yurloc** [comment]
It shouldn't in my opinion.

**Comment by triceo** [comment]
Ok, not merging for now.

**Comment by rsynek** [comment]
"Error:   [kiegroup/droolsjbpm-build-bootstrap] Trying to checking out kiegroup/droolsjbpm-build-bootstrap into '/home/runner/work/optaweb-employee-rostering/optaweb-employee-rostering/kiegroup_droolsjbpm_build_bootstrap'. It does not exist."

I am afraid that the current build chain does not work on the release branches.

**Comment by radtriste** [comment]
This should enable Jenkins Optaweb PR checks on release branches: https://github.com/kiegroup/optaplanner/pull/1499/

**Pull request merged**
