### PR TITLE
PLANNER-1729: Made the application builds on Windows

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
This comment is to confirm the Linux fixes did not break Windows

**Comment by yurloc** [comment]
I've squashed #336 to avoid broken commit message. @Christopher-Chianelli To avoid conflicts please run `git rebase windows-fixes~2 windows-fixes --onto master` after you pull to master.

**Comment by Christopher-Chianelli** [comment]
Cannot force push; pushing updated branch to my repo and deleting this one

**Comment by Christopher-Chianelli** [comment]
New PR: https://github.com/kiegroup/optaweb-employee-rostering/pull/342

**Pull request closed without merging**
