### PR TITLE
[7.x] remove springfox

### PR DESCRIPTION
**Pull request by Ginxo**
### Referenced pull requests
* https://github.com/kiegroup/optaweb-employee-rostering/pull/792
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1947

We could work on adding springdoc or even another kind of API library like the one this project uses on main branch, but I guess the effort vs the profit it's not worthy, wdyt?

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] tests</b>
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] LTS</b>

</details>

### CI Status

You can check OptaPlanner repositories CI status from [Chain Status webpage](https://kiegroup.github.io/optaplanner/).

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by yurloc** [comment]
Looking at amount of changes in this PR and given it's not even green yet, I would say it's not worth the effort. `7.x` is in maintenance mode so I'd only do security related version updates.

**Comment by Ginxo** [comment]
thanks @yurloc I totally understand your point. My ultimate purpose is to merge this one https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1947 I will try a final thing otherwise we will discard it, ok?

**Comment by yurloc** [comment]
> My ultimate purpose is to merge this one [kiegroup/droolsjbpm-build-bootstrap#1947](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1947)

If that's your goal, I'd suggest to simply move the `io.springfox` dependency management here. That should achieve the `kie-parent` cleanup and we can decide about SpringFox upgrade or replacement later. But as I said, unless it's necessary, I'd avoid touching it on `7.x`.

**Comment by mareknovotny** [comment]
yes, the suggested option to move the depMgmt down to optaweb is ok for me as it effectively removes it from our 7.x

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
moved to https://github.com/kiegroup/optaweb-employee-rostering/pull/815

**Pull request closed without merging**
