### PR TITLE
BXMSPROD-8: refactor to build without jboss-ip-bom

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/kie-soup/pull/95
https://github.com/kiegroup/appformer/pull/718
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/973
https://github.com/kiegroup/droolsjbpm-knowledge/pull/391
https://github.com/kiegroup/drools/pull/2396
https://github.com/kiegroup/optaplanner/pull/514
https://github.com/kiegroup/jbpm/pull/1503
https://github.com/kiegroup/kie-jpmml-integration/pull/5
https://github.com/kiegroup/droolsjbpm-integration/pull/1849
https://github.com/kiegroup/droolsjbpm-tools/pull/95
https://github.com/kiegroup/kie-uberfire-extensions/pull/85
https://github.com/kiegroup/kie-wb-playground/pull/76
https://github.com/kiegroup/kie-wb-common/pull/2710
https://github.com/kiegroup/drools-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/339
https://github.com/kiegroup/jbpm-designer/pull/854
https://github.com/kiegroup/jbpm-wb/pull/1364
https://github.com/kiegroup/kie-docs/pull/1645
https://github.com/kiegroup/kie-wb-distributions/pull/940
https://github.com/kiegroup/optaweb-employee-rostering/pull/250

**Comment by yurloc** [comment]
Build is blocked by a problem in `drools` repository:

 'dependencies.dependency.version' for org.jpmml:pmml-model:jar is missing. @ org.kie:kie-dmn-core:[unknown-version], /home/jenkins/workspace/KIE/master/pullrequest/optaweb-employee-rostering-pullrequests/upstream-repos/drools/kie-dmn/kie-dmn-core/pom.xml, line 103, column 17

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by yurloc** [comment]
This time:

13:56:02 **[kie-wb-common]** $ /opt/tools/apache-maven-3.5.2/bin/mvn -B -e -T1C -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true clean install
13:56:03 [INFO] Maven-Manipulation-Extension 2.13.1 ( SHA: 7bd176c6 ) 
13:56:03 [INFO] Error stacktraces are turned on.
13:56:04 INFO o.c.m.ext.manip.ManipulationManager - Maven-Manipulation-Extension: No changes.
13:56:04 INFO o.c.m.ext.manip.ManipulationManager - Maven-Manipulation-Extension: Finished.
13:56:04 [INFO] Scanning for projects...
13:56:13 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
13:56:13 [ERROR] **'dependencies.dependency.version'** for **org.uberfire:uberfire-social-activities-api:jar is missing**. @ **org.kie.workbench.stunner:kie-wb-common-stunner-showcase-standalone:[unknown-version]**, /home/jenkins/workspace/KIE/master/pullrequest/optaweb-employee-rostering-pullrequests/upstream-repos/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml, line 778, column 17
13:56:13 [ERROR] 'dependencies.dependency.version' for org.uberfire:uberfire-social-activities-api:jar is missing. @ **org.kie.workbench:kie-wb-common-dmn-webapp:[unknown-version]**, /home/jenkins/workspace/KIE/master/pullrequest/optaweb-employee-rostering-pullrequests/upstream-repos/kie-wb-common/kie-wb-common-dmn/kie-wb-common-dmn-webapp/pom.xml, line 857, column 17
13:56:13  @ 
13:56:13 [ERROR] The build could not read 2 projects -> [Help 1]

**Comment by yurloc** [comment]
Looks like there's a missing PR to kiegroup/jbpm-work-items.

**Comment by mareknovotny** [comment]
@yurloc you are right it was probably missed by @mbiarnes https://github.com/mbiarnes/jbpm-work-items/tree/replaceIPBOM

**Comment by yurloc** [comment]
Finally, the build has reached optaweb-employee-rostering. Now the GWT compilation fails:

15:00:59 [INFO] --- gwt-maven-plugin:1.0-rc-9:compile (default-compile) @ employee-rostering-gwtui ---
15:00:59 [INFO] Loading inherited module 'org.optaweb.employeerostering.gwtui.WorkerRosteringWebapp'
15:00:59 [INFO]    Loading inherited module 'org.gwtbootstrap3.extras.tagsinput.TagsInput'
15:00:59 [INFO]       [ERROR] Unable to find 'org/gwtbootstrap3/extras/tagsinput/TagsInput.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

@mbiarnes are you able to track this down?

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
@yurloc that compilation error is on my local too, I just removed that line and it worked fine

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Pull request merged**
