### PR TITLE
Distribution module should not be packaging jar

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Comment by yurloc** [comment]
JIRA for the separate executable JAR module: https://issues.jboss.org/browse/PLANNER-1737.

**Comment by Christopher-Chianelli** [comment]
I  am curious why the application fails to start in Travis (and Jenkins):
```
[INFO] --- process-exec-maven-plugin:0.9:start (start-backend-service) @ employee-rostering-distribution ---

[INFO] arg: java

[INFO] arg: -Dspring.profiles.active=dev

[INFO] arg: -Dserver.port=8180

[INFO] arg: -jar

[INFO] arg: employee-rostering-distribution-7.31.0-SNAPSHOT-exec.jar

[INFO] Full command line: java -Dspring.profiles.active=dev -Dserver.port=8180 -jar employee-rostering-distribution-7.31.0-SNAPSHOT-exec.jar

[INFO] Starting process: Run application

[INFO] Using working directory for this process: /home/travis/build/kiegroup/optaweb-employee-rostering/employee-rostering-distribution/target

Exception in thread "Thread-20" java.lang.RuntimeException: unexpected

	at com.bazaarvoice.maven.plugin.process.StdoutRedirector.run(StdoutRedirector.java:39)

Caused by: java.io.IOException: Stream Closed

	at java.io.FileOutputStream.writeBytes(Native Method)

	at java.io.FileOutputStream.write(FileOutputStream.java:326)

	at com.bazaarvoice.maven.plugin.process.StdoutRedirector.run(StdoutRedirector.java:34)
```

**Comment by Christopher-Chianelli** [comment]
(is the repackage plugin skipped because the type is pom?)

**Comment by yurloc** [comment]
@Christopher-Chianelli I think that is the reason. When I checked out this PR and built distribution locally, the execeutable JAR was missing.

**Comment by yurloc** [comment]
Will be addressed by #319.

**Pull request closed without merging**
