### PR TITLE
PLANNER-1672: Constraint configuration backend

### PR DESCRIPTION
**Pull request by cuijulian**
Jira: https://issues.jboss.org/browse/PLANNER-1672

Adds backend REST api for constraint configuration.
Requires frontend for user interaction.

### CODE REVIEW

**Comment by triceo** [comment]
This could come in very handy now.

**Comment by cuijulian** [comment]
> This could come in very handy now.

I thought this was merged! @triceo could you merge this please?

**Comment by cuijulian** [comment]
@triceo CI build passed, should be good to merge. Apologies for the delay, this PR completely slipped past me after it was approved.

**Comment by triceo** [comment]
Thanks, Julian! I'll attempt a port to the COVID branch now.

**Pull request merged**
