### PR TITLE
PLANNER-1271: Include Caused By infomation in Server's Stack Trace

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
@rsynek tried that, entity stream is closed (meaning no way to read entity body, which contains the stack trace, correct me if I am wrong).

**Comment by Christopher-Chianelli** [comment]
(I did it as an Integration Test, might be possible as a Unit Test)

**Comment by rsynek** [comment]
@Christopher-Chianelli might be possible that we have already read the content somewhere before?

**Comment by Christopher-Chianelli** [comment]
@rsynek For the IT test, if it was read, it would be inaccessible to us. The IT test I tried created a Spot, A Shift and then tries to delete the Spot (which create an exception with Caused By). It looked like this
```
Spot spot = spotRestService.addSpot(...);
assertClientResponseOk();
ShiftView shiftView = shiftRestService.addShift(...);
assertClientResponseOk();
assertThrowsExceptionOfType(Exception.class, () -> {spotRestService.remove(spot);});
ClientResponseAssert.(...).matches(cr -> {
BufferedReader reader = new BufferedReader(new InputStreamReader(cr.entityInputStream()));
String response = reader.lines().collect(Collectors.joining("\n"));
assertThat(response).contains("Caused By");
});
```

**Comment by Christopher-Chianelli** [comment]
It appears impossible to create a Unit Test to test this, since Response tries to access a non-existent Server class upon construction:
```
testCausedByInfomationIsSent(org.optaweb.employeerostering.server.common.jaxrs.OptaWebExceptionMapperTest)  Time elapsed: 0.013 s  <<< ERROR!
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at org.optaweb.employeerostering.server.common.jaxrs.OptaWebExceptionMapperTest.testCausedByInfomationIsSent(OptaWebExceptionMapperTest.java:35)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at org.optaweb.employeerostering.server.common.jaxrs.OptaWebExceptionMapperTest.testCausedByInfomationIsSent(OptaWebExceptionMapperTest.java:35
```
Merging PR without Tests

**Pull request merged**
