### PR TITLE
[WIP] AF-1799: Upgrade JDK 11 + GWT 2.9

### PR DESCRIPTION
**Pull request by caponetto**
**Upgrade JDK 11 + GWT 2.9**

Feel free to comment and/or raise any concerns.

This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039

Thanks guys for that!

**JIRA**:

[AF-1799](https://issues.redhat.com/browse/AF-1799)

**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by triceo** [comment]
@caponetto AFAIK this will remove compatibility with 8. It will use 11, and it will compile for 11. Is that what is necessary here?
Can we not simply use 11 and compile for 8?

**Comment by caponetto** [comment]
@triceo Yes, you're right. 
Probably this will be reverted. I'm just conducting some tests while the PRs are WIP.

**Comment by yurloc** [comment]
@triceo What's the reason for keeping compatibility with Java 8? It's EOL and I thought we were dropping it on master.

**Comment by triceo** [comment]
@yurloc AFAIK we'll be doing these changes to both `7.x` and `master`.
On `7.x`, bumping to Java 11 is - in my opinion - not even planned.
On `master`, I heard that the projects would move, but to the best of my knowledge it was never officially announced anywhere.

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins run fdb
Jenkins run cdb

**Pull request closed without merging**
